/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Meu Computador
 */
public class Evolucao_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Evolucao_GUI
     */
    public Evolucao_GUI() {
        initComponents();
        Model.Profissional_DAO.consultarEvolucao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome_lbl = new javax.swing.JLabel();
        evolucao_lbl = new javax.swing.JLabel();
        voltar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        especialidade_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(230, 250, 255));
        jPanel1.setLayout(null);

        nome_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nome_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nome_lbl);
        nome_lbl.setBounds(40, 70, 420, 30);

        evolucao_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        evolucao_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        evolucao_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 176, 194), 2, true));
        jPanel1.add(evolucao_lbl);
        evolucao_lbl.setBounds(50, 170, 390, 240);

        voltar_btn.setText("VOLTAR");
        voltar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltar_btn);
        voltar_btn.setBounds(200, 450, 100, 30);

        jLabel1.setBackground(new java.awt.Color(56, 176, 194));
        jLabel1.setFont(new java.awt.Font("Elephant", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 176, 194));
        jLabel1.setText("CONSULTA DE EVOLUÇÃO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 350, 40);

        especialidade_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        especialidade_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(especialidade_lbl);
        especialidade_lbl.setBounds(40, 110, 420, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btnActionPerformed
        dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_voltar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evolucao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evolucao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evolucao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evolucao_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evolucao_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel especialidade_lbl;
    public static javax.swing.JLabel evolucao_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel nome_lbl;
    public static javax.swing.JButton voltar_btn;
    // End of variables declaration//GEN-END:variables
}
