/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Meu Computador
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        evolucao_btn = new javax.swing.JButton();
        registrar_btn = new javax.swing.JButton();
        procedimento2_btn = new javax.swing.JButton();
        procedimento1_btn1 = new javax.swing.JButton();
        titulo_lbl = new javax.swing.JLabel();
        sair_btn = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(230, 250, 255));
        jPanel1.setLayout(null);

        evolucao_btn.setText("Evolução");
        evolucao_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 176, 194), 2, true));
        evolucao_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evolucao_btnActionPerformed(evt);
            }
        });
        jPanel1.add(evolucao_btn);
        evolucao_btn.setBounds(80, 370, 120, 50);

        registrar_btn.setText("Registro");
        registrar_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 176, 194), 2, true));
        registrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(registrar_btn);
        registrar_btn.setBounds(80, 290, 120, 50);

        procedimento2_btn.setText("Procedimento 2");
        procedimento2_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 176, 194), 2, true));
        procedimento2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedimento2_btnActionPerformed(evt);
            }
        });
        jPanel1.add(procedimento2_btn);
        procedimento2_btn.setBounds(80, 210, 120, 50);

        procedimento1_btn1.setText("Procedimento 1");
        procedimento1_btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 176, 194), 2, true));
        procedimento1_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedimento1_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(procedimento1_btn1);
        procedimento1_btn1.setBounds(80, 130, 120, 50);

        titulo_lbl.setFont(new java.awt.Font("Elephant", 1, 22)); // NOI18N
        titulo_lbl.setForeground(new java.awt.Color(56, 176, 194));
        titulo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_lbl.setText("ESCOLHA UMA OPÇÃO:");
        jPanel1.add(titulo_lbl);
        titulo_lbl.setBounds(90, 30, 320, 50);

        sair_btn.setText("SAIR");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(390, 460, 90, 23);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(250, 160, 220, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_btnActionPerformed
        dispose();
        new Registro_GUI().setVisible(true);
    }//GEN-LAST:event_registrar_btnActionPerformed

    private void procedimento2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedimento2_btnActionPerformed
        dispose();
        new Procedimento2_GUI().setVisible(true);
    }//GEN-LAST:event_procedimento2_btnActionPerformed

    private void evolucao_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evolucao_btnActionPerformed
        dispose();
        new Evolucao_GUI().setVisible(true);
    }//GEN-LAST:event_evolucao_btnActionPerformed

    private void procedimento1_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedimento1_btn1ActionPerformed
        dispose();
        new Procedimento_GUI().setVisible(true);
    }//GEN-LAST:event_procedimento1_btn1ActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton evolucao_btn;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static javax.swing.JButton procedimento1_btn1;
    public static javax.swing.JButton procedimento2_btn;
    public static javax.swing.JButton registrar_btn;
    public static javax.swing.JButton sair_btn;
    private javax.swing.JLabel titulo_lbl;
    // End of variables declaration//GEN-END:variables
}
